services:
  solver_qpoases:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - TIMEOUT=20
    command: /bin/bash -c "
      cd /root/solver-qpoases
      && pip install . --break-system-packages
      && qpoases_example"
